name: Build Kivy Applications

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-linux:
    name: Build Linux executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev python3-pip build-essential git zip libffi-dev libssl-dev libegl1 libgles2-mesa-dev patchelf

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build Linux executable
        run: |
          pyinstaller --name=kivy_stress_tester --onefile app/main.py

      - name: Upload Linux executable
        uses: actions/upload-artifact@v3
        with:
          name: Linux-Executable
          path: dist/kivy_stress_tester

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows EXE
        run: |
          pyinstaller --name=kivy_stress_tester --onefile app/main.py

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v3
        with:
          name: Windows-EXE
          path: dist/kivy_stress_tester.exe

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake libltdl-dev
          export PATH=$PATH:~/.local/bin/
          pip install --upgrade cython
          pip install buildozer

      - name: Build Android APK
        working-directory: app
        run: |
          buildozer -v android release

      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: Android-APK
          path: app/bin/*.apk
